### ISSUE TITLE
Fails without error message

### ISSUE THREAD

**Issue by radumas** [tannerjt/AGStoShapefile#1]
Hi,

Running 
```bash
Ubuntu 14.04.3 LTS
$node -v
v0.10.25
```

I'm trying to download [this](http://maps.cityofboston.gov/ArcGIS/rest/services/BaseServices/Bike_network/MapServer/1) and [that](http://maps.cityofboston.gov/ArcGIS/rest/services/BaseServices/Bike_network/MapServer/2). I'm copying and pasting the link to the REST endpoint and have a `services.txt` which looks like.
```bash
http://maps.cityofboston.gov/ArcGIS/rest/services/BaseServices/Bike_network/MapServer/2?f=json&pretty=true|30year
http://maps.cityofboston.gov/ArcGIS/rest/services/BaseServices/Bike_network/MapServer/1?f=json&pretty=true|5year
```
When I run `node AGStoSHP.js` I get
```bash
creating 5year geojson
creating 30year geojson
```
but the contents of `output` are merely `placeholder.txt`

**Comment by radumas** [comment]
I got it to work by deleting everything in the URL after "?", but still think some sort of error message should've printed

**Comment by tannerjt** [comment]
Thanks radumas.  I'll add better error handling and messaging for errors like this.  I'm glad you were able to get it to work.  Let me know if you run into any other issues.

**Comment by radumas** [comment]
Hey Tanner,

I was a bit premature in celebrating success. I produced files, but those contain no data. Could you have a look at those layers? I don't really understand ArcGIS REST, so it could just be that the data isn't downloadable....

Thanks!

**Comment by tannerjt** [comment]
I'm looking for a solution now.  The issue is that for some reason that service does not want to return its' geometry via the query interface.  This may be an issue with their setup of ArcGIS Server in particular, but I'd like to see if there is something I can do.

**Comment by tannerjt** [comment]
Radumas, I've just pushed some changes that will fix the issues you addressed.  First, I've added a 'mixin' capability to mix in your query params (f=json&format=pretty&etc=etc).  Second, I've made some changes to the query capabilities.  For these particular services, you will need to change the url slightly to query the FeatureServer.  The changes you should make to your text file are below:

http://maps.cityofboston.gov/ArcGIS/rest/services/BaseServices/Bike_network/FeatureServer/2?f=json&pretty=true|30year
http://maps.cityofboston.gov/ArcGIS/rest/services/BaseServices/Bike_network/FeatureServer/1?f=json&pretty=true|5year

This should work and works on my end.

**Comment by radumas** [comment]
Success! 

Thanks
