### ISSUE TITLE
 module ogr2ogr not found, tried npm install but got errors

### ISSUE THREAD

**Issue by kflaw** [tannerjt/AGStoShapefile#10]
I tried the suggestion in the closed issue, but get these errors below. Also, when I type ogr2ogr in windows command line it recognizes it. I've also a gist containing the debug log.
![error](https://cloud.githubusercontent.com/assets/9289048/16207351/7338b1ac-36e1-11e6-8bb1-5c2b64f53212.png)

https://gist.github.com/kflaw/3110e46bb9dc2ebc5b66331f96cc1505

**Comment by tannerjt** [comment]
You may want to try upgrading node on your windows machine [See documentation](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows)

**Comment by kflaw** [comment]
Thanks for the reply. I tried to update on windows but still am not having luck. Will need to get back to that. I'm now trying on a mac, and have gotten a little further but now am getting this error:

<img width="662" alt="screen shot 2016-06-20 at 4 47 16 pm" src="https://cloud.githubusercontent.com/assets/9289048/16213750/b0d37e28-3706-11e6-8a9b-be7b89231f2b.png">

**Comment by tannerjt** [comment]
I just made an update that will fix this particular error, but maybe not the underlying problem.  Can you do a `git pull origin master` and try running again.  Also, can you provide the URL to the ArcGIS REST Service?  If you are specifically trying to get GeoJSON, you might also look at this library [Esri-dump](https://github.com/openaddresses/esri-dump)

**Comment by kflaw** [comment]
Thanks for that, I just tried again and am now getting a different error. I will check out the other library you suggested.

<img width="770" alt="screen shot 2016-06-20 at 5 30 11 pm" src="https://cloud.githubusercontent.com/assets/9289048/16214412/cf070a80-370c-11e6-8966-34225fe1cb78.png">

**Comment by kflaw** [comment]
also here is a link to the service layer I'm tried to get

https://gisrevprxy.seattle.gov/ArcGIS/rest/services/SDOT_EXT/sdot_parking/MapServer/5

**Comment by tannerjt** [comment]
should be fixed now.

**Comment by pbrooke** [comment]
Thanks so much, this is an amazing script in every way!. I had this problem initially. What I did to get past it was to use the npm install command for each module the script uses. IE "npm install ogr2ogr". Works amazingly! Thanks again.

**Comment by tannerjt** [comment]
Thanks for posting this, and I'm glad it works well and is helpful for you.  I'll keep updating as I get time.
