### ISSUE TITLE
Getting the following error: throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by Trashmonk** [tannerjt/AGStoShapefile#26]
Hi, I am getting the following error:

info: Number of features for service:  2848
info: Getting chunks of 100 features...
info: query -> 0 out of 2848
info: query -> 100 out of 2848
info: query -> 200 out of 2848
info: query -> 300 out of 2848
info: query -> 400 out of 2848
info: query -> 500 out of 2848
info: query -> 600 out of 2848
info: query -> 700 out of 2848
info: query -> 800 out of 2848
info: query -> 900 out of 2848
info: query -> 1000 out of 2848
info: query -> 1100 out of 2848
info: query -> 1200 out of 2848
info: query -> 1300 out of 2848
info: query -> 1400 out of 2848
info: query -> 1500 out of 2848
info: query -> 1600 out of 2848
info: query -> 1700 out of 2848
info: query -> 1800 out of 2848
info: query -> 1900 out of 2848
info: query -> 2000 out of 2848
info: query -> 2100 out of 2848
info: query -> 2200 out of 2848
info: query -> 2300 out of 2848
info: query -> 2400 out of 2848
info: query -> 2500 out of 2848
info: query -> 2600 out of 2848
info: query -> 2700 out of 2848
info: query -> 2800 out of 2848
info: Number of features for service:  950
info: Getting chunks of 100 features...
info: query -> 0 out of 950
info: query -> 100 out of 950
info: query -> 200 out of 950
info: query -> 300 out of 950
info: query -> 400 out of 950
info: query -> 500 out of 950
info: query -> 600 out of 950
info: query -> 700 out of 950
info: query -> 800 out of 950
info: query -> 900 out of 950
info: Number of features for service:  144
info: Getting chunks of 100 features...
info: query -> 0 out of 144
info: query -> 100 out of 144
info: all requests settled
info: creating Point Features json
info: Creating Esri JSON
info: Creating GeoJSON
info: Creating Shapefile

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: ENOENT, open './output/Point Features.json'

Any help would be greatly appreciated!

Janosch

**Comment by Trashmonk** [comment]
I saw the question has been already been answered. Thank you. Works great.

**Comment by tannerjt** [comment]
Thanks, glad it's working.
