### ISSUE TITLE
Shapefile issue

### ISSUE THREAD

**Issue by gdink1020** [tannerjt/AGStoShapefile#27]
**I'm having issues getting AGStoShapefile to work on the following link...**

http://gis.publicaccessnow.com/arcgis/rest/services/ScottKs/ScottKsDynamic/MapServer

**When the script is ran it creates the following in the "output" folder...**

![capture](https://cloud.githubusercontent.com/assets/26913361/24686297/90e5af14-1978-11e7-94bb-77a4e5b0b617.PNG)

**Below is what the script looks like when it runs**

`C:\Users\(BLANK)\Desktop\AGStoShapefile-bigdata>node agstoshp.js
(node:5624) DeprecationWarning: process.EventEmitter is deprecated. Use require('events') instead.
info: Number of features for service:  4293
info: Getting chunks of 20 features...
info: query -> 0 out of 4293
info: query -> 20 out of 4293
info: query -> 40 out of 4293
info: query -> 60 out of 4293
info: query -> 80 out of 4293
info: query -> 100 out of 4293
info: query -> 120 out of 4293
info: query -> 140 out of 4293
info: query -> 160 out of 4293
info: query -> 180 out of 4293
info: query -> 200 out of 4293
info: query -> 220 out of 4293
info: query -> 240 out of 4293
info: query -> 260 out of 4293
info: query -> 280 out of 4293
info: query -> 300 out of 4293
info: query -> 320 out of 4293
info: query -> 340 out of 4293
info: query -> 360 out of 4293
info: query -> 380 out of 4293
info: query -> 400 out of 4293
info: query -> 420 out of 4293
info: query -> 440 out of 4293
info: query -> 460 out of 4293
info: query -> 480 out of 4293
info: query -> 500 out of 4293
info: query -> 520 out of 4293
info: query -> 540 out of 4293
info: query -> 560 out of 4293
info: query -> 580 out of 4293
info: query -> 600 out of 4293
info: query -> 620 out of 4293
info: query -> 640 out of 4293
info: query -> 660 out of 4293
info: query -> 680 out of 4293
info: query -> 700 out of 4293
info: query -> 720 out of 4293
info: query -> 740 out of 4293
info: query -> 760 out of 4293
info: query -> 780 out of 4293
info: query -> 800 out of 4293
info: query -> 820 out of 4293
info: query -> 840 out of 4293
info: query -> 860 out of 4293
info: query -> 880 out of 4293
info: query -> 900 out of 4293
info: query -> 920 out of 4293
info: query -> 940 out of 4293
info: query -> 960 out of 4293
info: query -> 980 out of 4293
info: all requests settled
info: creating Logan_Co_0000 json
info: Creating Esri JSON
info: Creating GeoJSON
info: Creating Shapefile
info: query -> 1000 out of 4293
info: query -> 1020 out of 4293
info: query -> 1040 out of 4293
info: query -> 1060 out of 4293
info: query -> 1080 out of 4293
info: query -> 1100 out of 4293
info: query -> 1120 out of 4293
info: query -> 1140 out of 4293
info: query -> 1160 out of 4293
info: query -> 1180 out of 4293
info: query -> 1200 out of 4293
info: query -> 1220 out of 4293
info: query -> 1240 out of 4293
info: query -> 1260 out of 4293
info: query -> 1280 out of 4293
info: query -> 1300 out of 4293
info: query -> 1320 out of 4293
info: query -> 1340 out of 4293
info: query -> 1360 out of 4293
info: query -> 1380 out of 4293
info: query -> 1400 out of 4293
info: query -> 1420 out of 4293
info: query -> 1440 out of 4293
info: query -> 1460 out of 4293
info: query -> 1480 out of 4293
info: query -> 1500 out of 4293
info: query -> 1520 out of 4293
info: query -> 1540 out of 4293
info: query -> 1560 out of 4293
info: query -> 1580 out of 4293
info: query -> 1600 out of 4293
info: query -> 1620 out of 4293
info: query -> 1640 out of 4293
info: query -> 1660 out of 4293
info: query -> 1680 out of 4293
info: query -> 1700 out of 4293
info: query -> 1720 out of 4293
info: query -> 1740 out of 4293
info: query -> 1760 out of 4293
info: query -> 1780 out of 4293
info: query -> 1800 out of 4293
info: query -> 1820 out of 4293
info: query -> 1840 out of 4293
info: query -> 1860 out of 4293
info: query -> 1880 out of 4293
info: query -> 1900 out of 4293
info: query -> 1920 out of 4293
info: query -> 1940 out of 4293
info: query -> 1960 out of 4293
info: query -> 1980 out of 4293
info: all requests settled
info: creating Logan_Co_0001 json
info: Creating Esri JSON
info: Creating GeoJSON
info: Creating Shapefile
info: query -> 2000 out of 4293
info: query -> 2020 out of 4293
info: query -> 2040 out of 4293
info: query -> 2060 out of 4293
info: query -> 2080 out of 4293
info: query -> 2100 out of 4293
info: query -> 2120 out of 4293
info: query -> 2140 out of 4293
info: query -> 2160 out of 4293
info: query -> 2180 out of 4293
info: query -> 2200 out of 4293
info: query -> 2220 out of 4293
info: query -> 2240 out of 4293
info: query -> 2260 out of 4293
info: query -> 2280 out of 4293
info: query -> 2300 out of 4293
info: query -> 2320 out of 4293
info: query -> 2340 out of 4293
info: query -> 2360 out of 4293
info: query -> 2380 out of 4293
info: query -> 2400 out of 4293
info: query -> 2420 out of 4293
info: query -> 2440 out of 4293
info: query -> 2460 out of 4293
info: query -> 2480 out of 4293
info: query -> 2500 out of 4293
info: query -> 2520 out of 4293
info: query -> 2540 out of 4293
info: query -> 2560 out of 4293
info: query -> 2580 out of 4293
info: query -> 2600 out of 4293
info: query -> 2620 out of 4293
info: query -> 2640 out of 4293
info: query -> 2660 out of 4293
info: query -> 2680 out of 4293
info: query -> 2700 out of 4293
info: query -> 2720 out of 4293
info: query -> 2740 out of 4293
info: query -> 2760 out of 4293
info: query -> 2780 out of 4293
info: query -> 2800 out of 4293
info: query -> 2820 out of 4293
info: query -> 2840 out of 4293
info: query -> 2860 out of 4293
info: query -> 2880 out of 4293
info: query -> 2900 out of 4293
info: query -> 2920 out of 4293
info: query -> 2940 out of 4293
info: query -> 2960 out of 4293
info: query -> 2980 out of 4293
info: all requests settled
info: creating Logan_Co_0002 json
info: Creating Esri JSON
info: Creating GeoJSON
info: Creating Shapefile
info: query -> 3000 out of 4293
info: query -> 3020 out of 4293
info: query -> 3040 out of 4293
info: query -> 3060 out of 4293
info: query -> 3080 out of 4293
info: query -> 3100 out of 4293
info: query -> 3120 out of 4293
info: query -> 3140 out of 4293
info: query -> 3160 out of 4293
info: query -> 3180 out of 4293
info: query -> 3200 out of 4293
info: query -> 3220 out of 4293
info: query -> 3240 out of 4293
info: query -> 3260 out of 4293
info: query -> 3280 out of 4293
info: query -> 3300 out of 4293
info: query -> 3320 out of 4293
info: query -> 3340 out of 4293
info: query -> 3360 out of 4293
info: query -> 3380 out of 4293
info: query -> 3400 out of 4293
info: query -> 3420 out of 4293
info: query -> 3440 out of 4293
info: query -> 3460 out of 4293
info: query -> 3480 out of 4293
info: query -> 3500 out of 4293
info: query -> 3520 out of 4293
info: query -> 3540 out of 4293
info: query -> 3560 out of 4293
info: query -> 3580 out of 4293
info: query -> 3600 out of 4293
info: query -> 3620 out of 4293
info: query -> 3640 out of 4293
info: query -> 3660 out of 4293
info: query -> 3680 out of 4293
info: query -> 3700 out of 4293
info: query -> 3720 out of 4293
info: query -> 3740 out of 4293
info: query -> 3760 out of 4293
info: query -> 3780 out of 4293
info: query -> 3800 out of 4293
info: query -> 3820 out of 4293
info: query -> 3840 out of 4293
info: query -> 3860 out of 4293
info: query -> 3880 out of 4293
info: query -> 3900 out of 4293
info: query -> 3920 out of 4293
info: query -> 3940 out of 4293
info: query -> 3960 out of 4293
info: query -> 3980 out of 4293
info: all requests settled
info: creating Logan_Co_0003 json
info: Creating Esri JSON
info: Creating GeoJSON
info: Creating Shapefile
info: query -> 4000 out of 4293
info: query -> 4020 out of 4293
info: query -> 4040 out of 4293
info: query -> 4060 out of 4293
info: query -> 4080 out of 4293
info: query -> 4100 out of 4293
info: query -> 4120 out of 4293
info: query -> 4140 out of 4293
info: query -> 4160 out of 4293
info: query -> 4180 out of 4293
info: query -> 4200 out of 4293
info: query -> 4220 out of 4293
info: query -> 4240 out of 4293
info: query -> 4260 out of 4293
info: query -> 4280 out of 4293
info: all requests settled
info: creating Logan_Co_0004 json
info: Creating Esri JSON
info: Creating GeoJSON
info: Creating Shapefile`

After completion there is no shapefile in the output folder. I've read through the other issues, but can't find anything that is applicable. Any help would be appreciated @tannerjt

**Comment by tannerjt** [comment]
Does it look like valid GeoJSON?  You can drag and drop the file into http://geojson.io/.  From what I can tell, it is grabbing the Chunks since you are using the bigdata branch, but not creating the shapefile.

**Comment by gdink1020** [comment]
They each were valid GeoJSON files and you were correct, it was dividing it and not creating a shapefile. I ran it with the "master" version and it created the shapefile no problem. It took me longer to write my issue and respond to this than it did to fix my issue. Thank you very much. Great tool and support
