### ISSUE TITLE
what/where should I take a look for this error? service.txt has valid url

### ISSUE THREAD

**Issue by jkyoungchoi** [tannerjt/AGStoShapefile#3]
http://map.trueautomation.com/ArcGIS/rest/services/Brazos/MapServer/10|subdiv

C:\>node AGStoSHP.js
creating BZSchool json
creating BZSchool geojson
[Error: Error: spawn ogr2ogr ENOENT]
[Error: Error: spawn ogr2ogr ENOENT]
creating BZSchool shapefile
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Error: spawn ogr2ogr ENOENT
    at ChildProcess.<anonymous> (C:\node_modules\ogr2ogr\index.js:187:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)

**Comment by tannerjt** [comment]
What operating system are you running this on?

**Comment by jkyoungchoi** [comment]
it's win7 pro

**Comment by tannerjt** [comment]
I wonder if this has to do with needing GDAL installed on your machine.  Can you try installing and running again? (http://www.gisinternals.com/release.php)[http://www.gisinternals.com/release.php]  It seems to work fine on my machine.

**Comment by jkyoungchoi** [comment]
Do I need other than GDAL core?

**Comment by tannerjt** [comment]
That should be all you need.

**Comment by jkyoungchoi** [comment]
I see, I'll try uninstall and reinstall and see what's gonna happen. Feel like I need to reboot but just can't right now.
Thanks for help,

**Comment by jkyoungchoi** [comment]
It worked out!
Thanks

**Comment by tannerjt** [comment]
Awesome!  Glad it worked, hope the tool is useful for you.
