### ISSUE TITLE
module ogr2ogr not found

### ISSUE THREAD

**Issue by LintangGalihsukma** [tannerjt/AGStoShapefile#4]
Hi
i have an issue. why did appear this message when i tried to run the module:
" error: cannot find the module 'ogr2ogr'
![error message](https://cloud.githubusercontent.com/assets/16472468/12048949/d00d26fc-af13-11e5-861a-8d6ad016db55.jpg)

regards,

**Comment by tannerjt** [comment]
try running `npm install` in command line first
