### ISSUE TITLE
[TypeError: Cannot read property '0' of undefined]

### ISSUE THREAD

**Issue by skyoaks** [tannerjt/AGStoShapefile#7]
When I run the tool. see this error. Wonder what the reason is. Thanks

$ node AGStoSHP.js
[TypeError: Cannot read property '0' of undefined]

**Comment by mgregor-oa** [comment]
I have a similar error.  Any help would be great.  Thanks.

![js error](https://cloud.githubusercontent.com/assets/17341885/13183218/6723ccf8-d6fb-11e5-8d2d-2ea2d63abaa2.png)

**Comment by tesoromaps** [comment]
reads dynamic map services great. had same issue trying to download feature service.

**Comment by tannerjt** [comment]
Looks like some issue is happening when trying to request Ids only.  The request on line 35 is causing the issue.

**Comment by mgregor-oa** [comment]
Is there a way to fix it?

**Comment by tesoromaps** [comment]
Might ask gent who made it or i found workaround, it's a toolbox that
downloads feature service as shp. no 1000 record limit on the features i
tested.
http://epro.maps.arcgis.com/home/item.html?id=16e5cc64178941839eca62837f168ec9
Here's the link and zip file. Good luck

**Comment by mgregor-oa** [comment]
I don't have a username and password to the service I want to get.

**Comment by tannerjt** [comment]
All these errors should now be fixed with the latest commit.  If you pull the latest changes it should work fine.  The problem was that the 'request' method was inserting a special character in the url.  I just serialized and appended it manually.

**Comment by tannerjt** [comment]
If it works now with the latest update, let me know and I'll close the issue.
