### ISSUE TITLE
More Console Info?

### ISSUE THREAD

**Issue by sosukeinu** [tannerjt/AGStoShapefile#8]
Not so much an issue, as a suggestion. I haven't taken much time to dig into the source, so I'm not sure where these `console.log()`'s would go, but it would be great to have a little more info at the terminal prompt to know exactly what's going on with the service/script. Especially with rest services that have a max county of 1000, and have 100's of thousands (or even millions) of results. I let the service run for 9 hours in one go with no feedback. I finally quit it, but it would be great to know if it was actually doing something, or at what point the hang was occurring. Thank you for any consideration, or assistance you can offer.

**Comment by tannerjt** [comment]
Added feedback for status of script.
