### ISSUE TITLE
failed to export bigsize data

### ISSUE THREAD

**Issue by sanjeevyanala** [tannerjt/AGStoShapefile#9]
Here is a problem when export bigsize data from json to geojson & shapefile. how can i solve this issue. 

please help me for this issue.
Thank You.

**Comment by tannerjt** [comment]
Can you provide the REST endpoint you are trying to download.  I'm merging this with #8

**Comment by sanjeevyanala** [comment]
I have tried over 80 MB file, Sorry i can't provide my REST service endpoint. Please u can apply anyof your own service URL. Thank You

**Comment by mdusch** [comment]
I have a 480MB shp file that I am trying to grab:

https://services5.arcgis.com/GM2ldXfeLnrqaq3j/arcgis/rest/services/AllParcels/FeatureServer/0

I think the program has been running for something like 19 hours and has not had an error message or anything past the initial line to input node AGStoSHP.js.

**Comment by sanjeevyanala** [comment]
Finally did u get output ? Please try to solve the issue. And this tool
will work on any type of arcgis rest service and all arcgis server version
(latest 10.4) ?

Is there any programme to grab wms layer of geoserver (export to geojson),
If yes please provide information.

Thank you



*Thanks & Regards,*

*Sanjeeva Reddy <http://sanjeevareddyyanala.blogspot.in/> **Yanala
<http://sanjeevareddyyanala.blogspot.in/>*

**Comment by mdusch** [comment]
No I had no output, I cancelled the process as the script was running for over a day - I mean I expected a couple of hours because of the amount of lines it had to process but not that long. Is there a max amount of calls that a single IP can grab from a server?

**Comment by sanjeevyanala** [comment]
​There is no max  amount of calls from IP, because we are grabing min 50 MB
file also having same problem.
Please try to solve this issue,..i am waiting for this. Thank u​



*Thanks & Regards,*

*Sanjeeva Reddy <http://sanjeevareddyyanala.blogspot.in/> **Yanala
<http://sanjeevareddyyanala.blogspot.in/>*

**Comment by tannerjt** [comment]
This is a problem due to running out of memory with JSON.stringify().  I tried to convert everything to streams but still get error.  You will need to break your query down into chunks using the URL Parameters available in the ArcGIS REST API.

**Comment by mdusch** [comment]
Would I still be able to use the services.txt file using these smaller chunks?

**Comment by tannerjt** [comment]
You can use the services.txt file.  You will need to pull the latest updates if you cloned the repo (`git pull origin master`) and do another `npm install` to get the latest packages.  You're query qould look something like this to reduce the payload:

https://services5.arcgis.com/GM2ldXfeLnrqaq3j/arcgis/rest/services/AllParcels/FeatureServer/0?where=FID<5000|parcels
https://services5.arcgis.com/GM2ldXfeLnrqaq3j/arcgis/rest/services/AllParcels/FeatureServer/0?where=FID>5000 and FID <10000|parcels

This would give you separate files with chunks of 5000 features.  I'll solicit help on this issue because streaming would alleviate this issue.

**Comment by tannerjt** [comment]
mdusch, were you able to solve this issue using the above solution?

**Comment by sanjeevyanala** [comment]
I will try, but i am not sure.



*Thanks & Regards,*

*Sanjeeva Reddy <http://sanjeevareddyyanala.blogspot.in/> **Yanala
<http://sanjeevareddyyanala.blogspot.in/>*

**Comment by mdusch** [comment]
I was able to almost run the entire area through the script, but ran into some issues with the script. I the service had 289718 features.

If I ran all queries in a row:

I first got it to work for 2 of 5 queries for the following services (specifically parcels2 and parcels5):
The rest had the same error - Cannot read property '0' of undefined.
```
https://services5.arcgis.com/GM2ldXfeLnrqaq3j/arcgis/rest/services/AllParcels/FeatureServer/0?where=FID>0 and FID <5000|parcels1
https://services5.arcgis.com/GM2ldXfeLnrqaq3j/arcgis/rest/services/AllParcels/FeatureServer/0?where=FID>5000 and FID <10000|parcels2
https://services5.arcgis.com/GM2ldXfeLnrqaq3j/arcgis/rest/services/AllParcels/FeatureServer/0?where=FID>10000 and FID <15000|parcels3
https://services5.arcgis.com/GM2ldXfeLnrqaq3j/arcgis/rest/services/AllParcels/FeatureServer/0?where=FID>15000 and FID <20000|parcels4
https://services5.arcgis.com/GM2ldXfeLnrqaq3j/arcgis/rest/services/AllParcels/FeatureServer/0?where=FID>20000 and FID <25000|parcels5
https://services5.arcgis.com/GM2ldXfeLnrqaq3j/arcgis/rest/services/AllParcels/FeatureServer/0?where=FID>25000 and FID <29000|parcels6
```
I used the same service.txt queries for the next run, except I only did one query at a time.

All parcels except Parcels3 ran fine, if I ran each query individually (maybe a longer pause is needed for large queries?)

Parcels3 would only create a json, but no geojson or zipped shp file. (TypeError: Cannot read property 'x' of undefined at toGeoJSON)

![image](https://cloud.githubusercontent.com/assets/19361662/16916537/4d55ffc6-4ccb-11e6-90c7-f797aa3c6061.png)







This was run with the newest build.

**Comment by mdusch** [comment]
I had to switch to OBJECTID to run a different query with the script (the file did not have an FID field), but what was weird was the script skipped 910-999 and 90-99. I was able to grab those features, and checked to see if they were not in the original query (they weren't) based off of another ID field in the feature class.

`http://oldhamgis.org:6080/arcgis/rest/services/LocalData/OLDHAM_BASEMAP/MapServer/5?where=PARCELS.OBJECTID>909 and PARCELS.OBJECTID <1000|OldH_Parcel_test1
http://oldhamgis.org:6080/arcgis/rest/services/LocalData/OLDHAM_BASEMAP/MapServer/5?where=PARCELS.OBJECTID>89 and PARCELS.OBJECTID <100|OldH_Parcel_test2`

**Comment by kramertamas** [comment]
I have corrected a bug (issue #13) and made the code work for large shapefiles. It will split a large shapefile but won't merge the parts.
 
[AGStoSHP.js.txt](https://github.com/tannerjt/AGStoShapefile/files/401866/AGStoSHP.js.txt)

**Comment by kramertamas** [comment]
On occasions, esri2geo stopped with an error (x is not a property of 'undefined'). It should be modified to check for typeof ft.geometry !== undefined. 

[esri2geo.js.txt](https://github.com/tannerjt/AGStoShapefile/files/401924/esri2geo.js.txt)

**Comment by tannerjt** [comment]
Thanks @kramertamas!  I've added a new branch called bigdata with your modifications.  I'd like to keep them as separate branches for now, as I need to test on my end.  I would recommend anybody running into larger dataset issues use your modifications.  Ideally, I would prefer to stream the output to a single file, but this is a great solution.

**Comment by mdusch** [comment]
@tannerjt just an FYI I tried out the new Bigdata pull with a dataset of about 90080 features. It failed after 30980 (Iteration 31) features with "TypeError: Cannot read property 'attributes' of undefined".

 I'll try splitting the amount of queries up in thirds to see if this will help.

**Comment by mdusch** [comment]
Update - Bigdata works fine in queries of 30,000. Still saves me a ton of time making query strings of 5000.

**Comment by rizkyfirmansyah** [comment]
Dear all,

I have the same issue to convert large datasets into shapefile, the same problem with @mdusch. Here the screenshot of the console.
![error](https://cloud.githubusercontent.com/assets/10456656/22493869/6bd917b8-e865-11e6-9a22-9e6f2d23451b.PNG)

The following ArcGIS REST service is in here: http://geoportal.menlhk.go.id/arcgis/rest/services/KLHK/BURN_AREA_20151028/MapServer/0

I have used the updated AGtoSHP.js to split huge data provided by @kramertamas, but nothing's work.

Please help me. Any thought is greatly appreciated.

Thank you.

**Comment by tannerjt** [comment]
Hey @rizkyfirmansyah .  This particular issue is happening because you are trying to run the script against a tiled map service.  Tiled maps will not work, as there is no geometry information, only tiles.  If you look at the root of the service:

http://geoportal.menlhk.go.id/arcgis/rest/services/KLHK/BURN_AREA_20151028/MapServer

You will see the the tiling scheme that lets you know this is a tiled map service, not a dynamic map service.

**Comment by rizkyfirmansyah** [comment]
Oooh I see. So it should be a dynamic map service to be able generated into a shapefile. Thank you for your explanation @tannerjt

**Comment by tannerjt** [comment]
I think we could use [request](https://github.com/request/request#streaming) and stream the original Esri JSON to file

```js
request('http://../arcgis/rest/.../0').pipe(fs.createWriteStream('file.json'))
```
